### ISSUE TITLE
In Percolation.java, why there's two WeightedQuickUF types? 

### ISSUE THREAD

**Issue by SAMSONEE** [mincong-h/algorithm-princeton#5]
Isn't using backwashQU enough?

**Comment by mincong-h** [comment]
Hi @SAMSONEE , thanks for opening the issue! The implementation was written in 2016 and I don't remember the question anymore. @nieldeokar changed the code last year. Nilesh, is there any chance that you can help answering this question? Otherwise, if you have a better solution, Samson, please submit a PR, that will be very welcome.

**Comment by nilesh-525** [comment]
Frankly speaking, even I don't remember what it was and why. I think it was failing one of the test cases so I made some changes. and @mincong-h happily accepted my PR.

**Comment by SAMSONEE** [comment]
I've figured out the reasons now: the normalQU is created to solve the backwash problem. The details are described here: [https://stackoverflow.com/questions/61396690/how-to-handle-the-backwash-problem-in-percolation-without-creating-an-extra-wuf](url)
Thanks for your timely feedback! @mincong-h @nilesh-525

**Comment by mincong-h** [comment]
Happy to see that you found the answer, @SAMSONEE !
